### PR TITLE
Raptoreum v17 with massive backports addoption from bitcoin and dash

### PR DESCRIPTION
**Pull request by malbit**
- Update crc32c subtree (ref: https://github.com/bitcoin/bitcoin/commit/fac1c13ead8da2414acdd3202040f00a21435b8f)
- Update univalue subtree (ref: https://github.com/bitcoin/bitcoin/commit/304319367595b51abfd69f1c4abddeef0acca3a9)
- Update leveldb subtree (ref: https://github.com/bitcoin/bitcoin/commit/20a6babfa9a66f5432ef19c6c433b4357560f853)
- refactor: depends build env
- refactor: build configuration (comply with autotools 2.69)
- Integrate univalue into our build system (ref: https://github.com/bitcoin/bitcoin/commit/0f95247246344510c9a51810c14c633abb382e95)
- crc32c build system integration (ref: https://github.com/bitcoin/bitcoin/commit/9ebdf047578f0da7e6578d0c51c32f55e84ac157)
- fixed placeholders at QT
- Support to checking HW functions at compile-time
- Support for HW 256-bit RNG (where available)

### CODE REVIEW

**Comment by ArqTras** [comment]
Looks avesome

**Review by chadouming — CHANGES_REQUESTED** [review]
randomenv.cpp 
Heater should be Hasher ?

**Comment by npq7721** [comment]
@malbit can u please resolve conflict? thanks

**Comment by malbit** [comment]
> @malbit can u please resolve conflict? thanks

Yet not finished codebase. Will resolve at the end when final RC will be prepared.

**Pull request merged**
