### PR TITLE
Enable Unit Test Automation

### LINKED ISSUE #206: Review/Update Unit Tests
# Review/Update Unit Tests

There are some unit tests that are failing (e.g., brought in from Dash using different chainparams).

Run the unit tests and review any that are failing.  Correct as needed.

### PR DESCRIPTION
**Pull request by CodeIsTheKey**
* Added automated unit tests to the x86 Ubuntu builds.
* Cleanup for build.yaml for consistency, action version updates.

This is the last PR for unit tests.  It resolves #206

### CODE REVIEW

**Comment by HumbleDeer** [comment]
Looks good! The consistent and verbose naming is a much needed aspect. I'll let the approval to one of the other people. :) I'm not yet confident approving this in my own.

**Review by nandofw — APPROVED** [review]
LGTM

**Review by npq7721 — APPROVED** [review]
LGTM

**Comment by CodeIsTheKey** [comment]
Resolves #206

**Pull request merged**
