### PR TITLE
v0.16 v0.17

### PR DESCRIPTION
**Pull request by malbit**
QT need rework
v16 + v17 merged together

### CODE REVIEW

**Comment by npq7721** [comment]
@malbit please resolve conflicts first. thanks

**Review by npq7721 — COMMENTED** [review]
@malbit please resolve conflicts first

**Comment by malbit** [comment]
> @malbit please resolve conflicts first

I am working at it and fixing typos as well.

**Review by npq7721 — DISMISSED** [review]
temporarily approve to take a closer look at conflicts

**Review by npq7721 — APPROVED** [review]
Approve to merge so that we can have follow up PR to fix build error and any other missing features

**Pull request merged**
